apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: ameni1/5arctict7-amenimensi-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
